In [1]:
import os
import tqdm
import numpy as np
import pandas as pd
from glob import glob

In [7]:
stockList = ["ABT","HON","AEP","BA","BMY","CPB","CAT","CVX","KO","CL","ED","GLW","DE","DTE","D","ETN","XOM","F","GD","GE","HAL","HSY","IBM","IP","K","KMB","KR","SPGI","CVS","MRK","ETR","MMM","MSI","NSC","XEL","FE","PPG","SRE","PEP","PFE","EXC","MO","COP","PG","PEG","ROK","EIX","SO","TXN","UNP","WY","WHR","XRX","SHW","CMI","EMR","SLB","CSX","CLX","GIS","NEM","MCD","LLY","BAX","BDX","JNJ","GPC","HPQ","WMB","IFF","AXP","CI","JPM","TAP","DIS","DUK","NEE","LNC","BAC","WFC","TGT","INTC","TXT","VFC","WBA","AIG","FDX","PCAR","ADP","GWW","MAS","ADM","WMT","SNA","SWK","BF.B","AAPL","OXY","CAG","LB","VZ","T","LOW","PHM","HES","LMT","HAS","BLL","APD","NUE","PKI","NOC","CNP","TJX","DOV","PH","ITW","JCI","GPS","JWN","MDT","HRB","SYY","MMC","AVY","HD","PNC","C","NKE","ECL","NWL","ORCL","ADSK","MRO","AEE","AMGN","LIN","IPG","COST","CSCO","EMN","KEY","UNM","MSFT","LUV","UNH","VIAC","MU","BSX","AMAT","BK","L","DRI","ALL","FCX","MS","PPL","CMA","HUM","HIG","FITB","TMO","AZO","ADBE","CAH","SCHW","EFX","APA","PGR","HBAN","STT","KLAC","YUM","TFC","CINF","OMC","NTRS","SEE","BEN","MAR","COF","WM","KSS","RF","PAYX","AES","DHR","CCL","USB","MCK","CTL","AGN","CMS","AFL","NTAP","BBY","VMC","QCOM","PNW","ADI","TROW","LEG","XLNX","CTXS","HOG","A","SBUX","TIF","DVN","MCO","NI","EOG","RHI","INTU","MET","SYK","CTAS","FISV","ZION","ZBH","ABC","NVDA","EQR","WAT","SPG","UPS","EA","EBAY","GS","PRU","PFG","ANTM","TRV","CMCSA","DGX","AIV","MKC","NLOK","PLD","BIIB","MTB","ETFC","MYL","VLO","GILD","TPR","LH","NOV","STZ","DHI","TSN","VNO","PSA","AMP","LEN","AMZN","EL","VRSN","KIM","BXP","GOOGL","JNPR","CME","WU","FIS","CBRE","CTSH","AVB","RL","VAR","CHRW","HST","MDLZ","AIZ","DFS","AKAM","MCHP","ICE","EXPE","NBL","EXPD","J","AMT","PM","ISRG","COG","MA","DVA","IVZ","CF","FAST","CRM","PXD","APH","FLS","NDAQ","WEC","SJM","PBCT","XRAY","WYNN","RSG","FLIR","IRM","WELL","HRL","VTR","ES","ORLY","WDC","PWR","FMC","BKNG","ROST","V","ROP","NRG","BRK.B","HP","DISCA","OKE","CERN","KMX","CB","FFIV","NFLX","EW","BLK","CMG","MPC","ACN","MOS","TEL","XYL","PRGO","BWA","DLTR","CCI","PSX","KMI","ALXN","LRCX","MNST","STX","LYB","PNR","DG","GRMN","APTV","ABBV","PVH","REGN","KSU","GM","ZTS","NWSA","NLSN","DAL","AME","VRTX","CPRI","ALLE","MHK","ADS","FB","TSCO","ESS","GOOGL","UAA","AVGO","MLM","DISCA","UHS","URI","RCL","HCA","SWKS","HSIC","AAL","SLG","EQIX","HBI","O","QRVO","JBHT","WRK","KHC","AAP","PYPL","ATVI","UAL","NWSA","VRSK","HPE","SYF","ILMN","CHD","WLTW","EXR","FRT","CFG","CXO","AWK","UDR","HOLX","CNC","UAA","ULTA","GPN","ALK","DLR","LKQ","AJG","TDG","FBHS","LNT","ALB","FTV","MTD","CHTR","COO","COTY","HWM","MAA","IDXX","FTI","INCY","CBOE","REG","DISH","SNPS","AMD","RJF","ARE","DXC","IT","INFO","HLT","RE","ANSS","ALGN","BKR","AOS","DRE","MGM","RMD","PKG","IQV","SBAC","CDNS","NCLH","HII","IPGP","SIVB","TTWO","MSCI","ABMD","EVRG","TWTR","HFC","BR","FLT","CPRT","ANET","ROL","FTNT","KEYS","JKHY","MXIM","LW","FANG","CE","FRC","TFX","ATO","WAB","FOXA","FOXA","DOW","CTVA","DD","AMCR","MKTX","LHX","TMUS","IEX","LDOS","GL","CDW","NVR","LVS","PEAK","NOW","WRB","ODFL","ZBRA","STE","LYV","PAYC","TT","IR","AON","OTIS","CARR","RTX"]
priceData = pd.DataFrame([])
sectorMap = {}
ratingMap = {}

In [3]:
for file in tqdm.tqdm_notebook(glob(os.getcwd() + '/dataset/*.csv'), desc='1st loop'):
    data = pd.read_csv(file)
    data['datadate'] = pd.to_datetime(data['datadate'], format='%Y/%m/%d')
    
    
    for index, row in tqdm.tqdm_notebook(data.iterrows(), desc='2nd loop'):
        if row['tic'] in stockList:
            priceData.loc[row['datadate'], row['tic']] = row['prcod']
            sectorMap[row['tic']] = row['gsector']
            ratingMap[row['tic']] = row['spcsrc']

HBox(children=(IntProgress(value=0, description='1st loop', max=6, style=ProgressStyle(description_width='init…

/opt/conda/lib/python3.7/site-packages/IPython/core/interactiveshell.py:3058: DtypeWarning: Columns (1) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

HBox(children=(IntProgress(value=1, bar_style='info', description='2nd loop', max=1, style=ProgressStyle(descr…

HBox(children=(IntProgress(value=1, bar_style='info', description='2nd loop', max=1, style=ProgressStyle(descr…

HBox(children=(IntProgress(value=1, bar_style='info', description='2nd loop', max=1, style=ProgressStyle(descr…

HBox(children=(IntProgress(value=1, bar_style='info', description='2nd loop', max=1, style=ProgressStyle(descr…

HBox(children=(IntProgress(value=1, bar_style='info', description='2nd loop', max=1, style=ProgressStyle(descr…

HBox(children=(IntProgress(value=1, bar_style='info', description='2nd loop', max=1, style=ProgressStyle(descr…

In [4]:
priceData.sort_index(inplace=True)
priceData.head()

,PNW,APD,HES,AFL,AMGN,ADI,APA,AMAT,ADSK,AVY,...,TEL,V,ATVI,VRSK,AVGO,MPC,XYL,CPRI,LYB,ALLE
2010-01-04,36.66,82.11,61.84,46.50,56.63,31.79,104.940,14.05,25.61,36.74,...,24.82,88.00,11.230,30.41,18.30,NaN,NaN,NaN,NaN,NaN
2010-01-05,36.77,82.90,63.60,47.49,57.33,31.67,105.980,14.24,25.62,38.46,...,24.96,87.30,11.242,29.85,18.95,NaN,NaN,NaN,NaN,NaN
2010-01-06,36.34,82.00,63.31,49.83,56.94,31.71,106.780,14.23,25.15,36.89,...,24.66,87.01,11.260,30.00,18.95,NaN,NaN,NaN,NaN,NaN
2010-01-07,36.59,81.81,63.56,49.41,56.41,31.46,108.320,14.14,25.22,36.80,...,25.06,85.97,11.100,30.36,19.04,NaN,NaN,NaN,NaN,NaN
2010-01-08,36.54,81.14,64.62,49.66,56.07,31.20,106.115,14.24,25.40,37.11,...,24.66,86.82,10.970,30.21,18.90,NaN,NaN,NaN,NaN,NaN

In [16]:
priceData.tail()

,PNW,APD,HES,AFL,AMGN,ADI,APA,AMAT,ADSK,AVY,...,TEL,V,ATVI,VRSK,AVGO,MPC,XYL,CPRI,LYB,ALLE
2020-04-15,79.01,219.27,36.00,36.19,224.99,100.73,7.12,51.310,168.57,106.82,...,67.52,168.70,62.630,147.56,261.00,24.81,68.53,13.55,55.90,96.38
2020-04-16,79.88,214.44,34.86,35.71,225.00,101.52,7.96,51.870,171.46,107.66,...,65.88,167.11,66.454,148.31,261.76,24.01,66.76,13.55,52.46,94.37
2020-04-17,80.59,217.46,32.99,36.23,236.83,103.96,7.45,53.635,176.08,107.24,...,65.23,169.65,66.500,153.48,263.22,22.61,68.73,13.09,50.26,96.37
2020-04-20,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2020-04-21,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [5]:
sectorMap

{'PNW': 55,
 'APD': 15,
 'HES': 10,
 'AFL': 40,
 'AMGN': 35,
 'ADI': 45,
 'APA': 10,
 'AMAT': 45,
 'ADSK': 45,
 'AVY': 15,
 'BLL': 15,
 'BK': 40,
 'VZ': 50,
 'BBY': 25,
 'HRB': 25,
 'CAH': 35,
 'CTL': 50,
 'CMA': 40,
 'C': 40,
 'CMS': 55,
 'DHR': 35,
 'DOV': 20,
 'OMC': 50,
 'PKI': 35,
 'ECL': 15,
 'EFX': 20,
 'FITB': 40,
 'RF': 40,
 'USB': 40,
 'BEN': 40,
 'GPS': 25,
 'HAS': 25,
 'HD': 25,
 'CNP': 55,
 'HBAN': 40,
 'ITW': 20,
 'IPG': 50,
 'JCI': 20,
 'KLAC': 45,
 'LMT': 20,
 'L': 40,
 'LOW': 25,
 'MRO': 10,
 'MMC': 40,
 'MCK': 35,
 'MDT': 35,
 'MU': 45,
 'NWL': 25,
 'NKE': 25,
 'JWN': 25,
 'NTRS': 40,
 'NOC': 20,
 'NUE': 15,
 'PNC': 40,
 'PH': 20,
 'PAYX': 45,
 'PPL': 55,
 'PHM': 25,
 'SEE': 15,
 'KEY': 40,
 'LUV': 20,
 'T': 50,
 'STT': 40,
 'SYY': 30,
 'TMO': 35,
 'AEE': 55,
 'UNH': 35,
 'VMC': 15,
 'TJX': 25,
 'TFC': 40,
 'MS': 40,
 'MSFT': 45,
 'ORCL': 45,
 'ADBE': 45,
 'UNM': 40,
 'PGR': 40,
 'CCL': 25,
 'VIAC': 50,
 'SCHW': 40,
 'WM': 20,
 'FCX': 15,
 'CINF': 40,
 'CSCO': 45,
 'AZO': 25,
 'AES': 55,
 'QCOM': 45,
 'LIN': 15,
 'BSX': 35,
 'KSS': 25,
 'AGN': 35,
 'HUM': 35,
 'ALL': 40,
 'MAR': 25,
 'COST': 30,
 'EMN': 15,
 'COF': 40,
 'DRI': 25,
 'NTAP': 45,
 'HIG': 40,
 'YUM': 25,
 'RHI': 20,
 'STZ': 30,
 'CTAS': 20,
 'CMCSA': 50,
 'FLS': 20,
 'EXPD': 20,
 'MTB': 40,
 'J': 20,
 'LEG': 25,
 'LEN': 25,
 'HST': 60,
 'MKC': 30,
 'MYL': 35,
 'NBL': 10,
 'NI': 55,
 'SJM': 30,
 'PSA': 60,
 'SYK': 35,
 'TSN': 30,
 'UPS': 20,
 'VAR': 35,
 'VNO': 60,
 'WEC': 55,
 'ZION': 40,
 'TROW': 40,
 'HOG': 25,
 'FISV': 45,
 'TIF': 25,
 'XRAY': 35,
 'FAST': 20,
 'APH': 45,
 'PXD': 10,
 'DVN': 10,
 'LH': 35,
 'VLO': 10,
 'NLOK': 45,
 'PBCT': 40,
 'EOG': 10,
 'EA': 50,
 'COG': 10,
 'XLNX': 45,
 'BIIB': 35,
 'KIM': 60,
 'GILD': 35,
 'DHI': 25,
 'SBUX': 25,
 'INTU': 45,
 'MCHP': 45,
 'EQR': 60,
 'SPG': 60,
 'IVZ': 40,
 'AVB': 60,
 'PLD': 60,
 'AIV': 60,
 'ABC': 35,
 'DVA': 35,
 'EL': 30,
 'WAT': 35,
 'CTXS': 45,
 'TRV': 40,
 'ETFC': 40,
 'NOV': 10,
 'DGX': 35,
 'AMZN': 25,
 'RL': 25,
 'BXP': 60,
 'CHRW': 20,
 'VRSN': 45,
 'AMT': 60,
 'CTSH': 45,
 'EBAY': 25,
 'GS': 40,
 'NVDA': 45,
 'JNPR': 45,
 'AKAM': 45,
 'EXPE': 25,
 'A': 35,
 'MET': 40,
 'ISRG': 35,
 'MCO': 40,
 'TPR': 25,
 'MDLZ': 30,
 'PRU': 40,
 'ZBH': 35,
 'ANTM': 35,
 'PFG': 40,
 'CME': 40,
 'NDAQ': 40,
 'AIZ': 40,
 'CRM': 45,
 'MA': 45,
 'GOOGL': 50,
 'ICE': 40,
 'CF': 15,
 'AMP': 40,
 'FIS': 45,
 'WU': 45,
 'DFS': 40,
 'PM': 30,
 'CBRE': 60,
 'ABT': 35,
 'HON': 20,
 'AEP': 55,
 'BA': 20,
 'BMY': 35,
 'CPB': 30,
 'CAT': 20,
 'CVX': 10,
 'KO': 30,
 'CL': 30,
 'ED': 55,
 'GLW': 45,
 'DE': 20,
 'DTE': 55,
 'D': 55,
 'ETN': 20,
 'XOM': 10,
 'F': 25,
 'GD': 20,
 'GE': 20,
 'HAL': 10,
 'HSY': 30,
 'IBM': 45,
 'IP': 15,
 'K': 30,
 'KMB': 30,
 'KR': 30,
 'SPGI': 40,
 'CVS': 35,
 'MRK': 35,
 'ETR': 55,
 'MMM': 20,
 'MSI': 45,
 'NSC': 20,
 'XEL': 55,
 'FE': 55,
 'PPG': 15,
 'SRE': 55,
 'PEP': 30,
 'PFE': 35,
 'EXC': 55,
 'MO': 30,
 'COP': 10,
 'PG': 30,
 'PEG': 55,
 'AXP': 40,
 'AIG': 40,
 'AAPL': 45,
 'ADM': 30,
 'ADP': 45,
 'BAX': 35,
 'BDX': 35,
 'BF.B': 30,
 'CI': 35,
 'CSX': 20,
 'JPM': 40,
 'CLX': 30,
 'CAG': 30,
 'TAP': 30,
 'CMI': 20,
 'TGT': 25,
 'DIS': 50,
 'DUK': 55,
 'EMR': 20,
 'NEE': 55,
 'FDX': 20,
 'GIS': 30,
 'GPC': 25,
 'GWW': 20,
 'HPQ': 45,
 'INTC': 45,
 'IFF': 15,
 'JNJ': 35,
 'LLY': 35,
 'LB': 25,
 'LNC': 40,
 'MAS': 20,
 'MCD': 25,
 'BAC': 40,
 'NEM': 15,
 'WFC': 40,
 'OXY': 10,
 'PCAR': 20,
 'ROK': 20,
 'SLB': 10,
 'SHW': 15,
 'SNA': 20,
 'EIX': 55,
 'SO': 55,
 'SWK': 20,
 'TXN': 45,
 'TXT': 20,
 'UNP': 20,
 'VFC': 25,
 'WMT': 30,
 'WBA': 30,
 'WY': 60,
 'WHR': 25,
 'WMB': 10,
 'XRX': 45,
 'AMD': 45,
 'ALK': 20,
 'AON': 40,
 'DXC': 45,
 'COO': 35,
 'DD': 15,
 'ATO': 55,
 'AJG': 40,
 'LHX': 20,
 'HLT': 25,
 'HFC': 10,
 'TT': 20,
 'EVRG': 55,
 'RJF': 40,
 'ROL': 20,
 'AOS': 20,
 'TFX': 35,
 'GL': 40,
 'UDR': 60,
 'RTX': 20,
 'LNT': 55,
 'JKHY': 45,
 'COTY': 30,
 'IT': 45,
 'NVR': 25,
 'PEAK': 60,
 'CDNS': 45,
 'DRE': 60,
 'ABMD': 35,
 'MXIM': 45,
 'FRC': 40,
 'MGM': 25,
 'WRB': 40,
 'IEX': 20,
 'SIVB': 40,
 'TMUS': 50,
 'IQV': 35,
 'TWTR': 50,
 'PAYC': 45,
 'KEYS': 45,
 'ANET': 45,
 'HOLX': 35,
 'CFG': 40,
 'IDXX': 35,
 'ZBRA': 45,
 'ODFL': 20,
 'SNPS': 45,
 'STE': 35,
 'FTV': 20,
 'HWM': 20,
 'CDW': 45,
 'LW': 30,
 'REG': 60,
 'INCY': 35,
 'MAA': 60,
 'ALB': 15,
 'CPRT': 20,
 'IR': 20,
 'FTI': 10,
 'RMD': 35,
 'BKR': 10,
 'DOW': 15,
 'FOXA': 50,
 'CTVA': 15,
 'OTIS': 20,
 'CARR': 20,
 'DISH': 50,
 'WAB': 20,
 'RE': 40,
 'ANSS': 45,
 'TTWO': 50,
 'ARE': 60,
 'MTD': 35,
 'AMCR': 15,
 'NCLH': 25,
 'SBAC': 60,
 'CHTR': 50,
 'PKG': 15,
 'ALGN': 35,
 'GPN': 45,
 'CNC': 35,
 'TDG': 20,
 'LKQ': 25,
 'MKTX': 40,
 'DLR': 60,
 'LVS': 25,
 'CE': 15,
 'INFO': 20,
 'UAA': 25,
 'LDOS': 45,
 'LYV': 50,
 'FANG': 10,
 'NOW': 45,
 'IPGP': 45,
 'BR': 45,
 'CXO': 10,
 'MSCI': 40,
 'ULTA': 25,
 'AWK': 55,
 'FTNT': 45,
 'CBOE': 40,
 'FLT': 45,
 'HII': 20,
 'FBHS': 20,
 'AAL': 20,
 'SWKS': 45,
 'AME': 20,
 'BRK.B': 40,
 'CHD': 30,
 'DAL': 20,
 'DG': 25,
 'FMC': 15,
 'FRT': 60,
 'GM': 25,
 'WELL': 60,
 'KHC': 30,
 'HP': 10,
 'HRL': 30,
 'JBHT': 20,
 'KMI': 10,
 'KSU': 20,
 'LRCX': 45,
 'ES': 55,
 'OKE': 10,
 'PNR': 20,
 'PVH': 25,
 'ROST': 25,
 'UAL': 20,
 'UHS': 35,
 'WDC': 45,
 'CERN': 35,
 'ZTS': 35,
 'ABBV': 35,
 'NWSA': 50,
 'SYF': 40,
 'HCA': 35,
 'REGN': 35,
 'MNST': 30,
 'VRTX': 35,
 'PYPL': 45,
 'PRGO': 35,
 'ROP': 20,
 'MHK': 25,
 'HPE': 45,
 'CB': 40,
 'ORLY': 25,
 'RCL': 25,
 'FLIR': 45,
 'BWA': 25,
 'MLM': 15,
 'TSCO': 25,
 'WRK': 15,
 'ESS': 60,
 'O': 60,
 'DLTR': 25,
 'HSIC': 35,
 'ALXN': 35,
 'IRM': 60,
 'KMX': 25,
 'QRVO': 45,
 'SLG': 60,
 'URI': 20,
 'PWR': 20,
 'NLSN': 20,
 'VTR': 60,
 'RSG': 20,
 'CCI': 60,
 'APTV': 25,
 'BKNG': 25,
 'FFIV': 45,
 'BLK': 40,
 'EW': 35,
 'NRG': 55,
 'ILMN': 35,
 'EQIX': 60,
 'GRMN': 25,
 'ACN': 45,
 'ADS': 45,
 'WLTW': 40,
 'AAP': 25,
 'NFLX': 50,
 'WYNN': 25,
 'STX': 45,
 'EXR': 60,
 'MOS': 15,
 'DISCA': 50,
 'CMG': 25,
 'FB': 50,
 'PSX': 10,
 'HBI': 25,
 'TEL': 45,
 'V': 45,
 'ATVI': 50,
 'VRSK': 20,
 'AVGO': 45,
 'MPC': 10,
 'XYL': 20,
 'CPRI': 25,
 'LYB': 15,
 'ALLE': 20}

In [6]:
ratingMap

{'PNW': 'A',
 'APD': 'A-',
 'HES': 'B-',
 'AFL': 'A-',
 'AMGN': 'A-',
 'ADI': 'B+',
 'APA': 'B-',
 'AMAT': 'A-',
 'ADSK': 'C',
 'AVY': 'B+',
 'BLL': 'A-',
 'BK': 'A',
 'VZ': 'B',
 'BBY': 'B',
 'HRB': 'B+',
 'CAH': 'B+',
 'CTL': 'B-',
 'CMA': 'A-',
 'C': 'B',
 'CMS': 'A-',
 'DHR': 'A-',
 'DOV': 'B+',
 'OMC': 'A+',
 'PKI': 'B+',
 'ECL': 'A+',
 'EFX': 'B+',
 'FITB': 'A-',
 'RF': 'B+',
 'USB': 'A',
 'BEN': 'B+',
 'GPS': 'A-',
 'HAS': 'B+',
 'HD': 'A+',
 'CNP': 'B+',
 'HBAN': 'B+',
 'ITW': 'A',
 'IPG': 'B+',
 'JCI': 'B+',
 'KLAC': 'B+',
 'LMT': 'A',
 'L': 'B',
 'LOW': 'A+',
 'MRO': 'B-',
 'MMC': 'A',
 'MCK': 'B+',
 'MDT': 'B+',
 'MU': 'B-',
 'NWL': 'B',
 'NKE': 'A',
 'JWN': 'B+',
 'NTRS': 'A-',
 'NOC': 'A+',
 'NUE': 'A-',
 'PNC': 'A',
 'PH': 'A-',
 'PAYX': 'A+',
 'PPL': 'B+',
 'PHM': 'B',
 'SEE': 'B',
 'KEY': 'B+',
 'LUV': 'A-',
 'T': 'B',
 'STT': 'A-',
 'SYY': 'B+',
 'TMO': 'A',
 'AEE': 'A-',
 'UNH': 'A+',
 'VMC': 'B',
 'TJX': 'A',
 'TFC': 'B+',
 'MS': 'B+',
 'MSFT': 'B+',
 'ORCL': 'A-',
 'ADBE': 'B',
 'UNM': 'A-',
 'PGR': 'B+',
 'CCL': 'B+',
 'VIAC': 'A',
 'SCHW': 'A',
 'WM': 'B+',
 'FCX': 'C',
 'CINF': 'B+',
 'CSCO': 'B+',
 'AZO': 'B+',
 'AES': 'B-',
 'QCOM': 'B',
 'LIN': 'A',
 'BSX': 'B-',
 'KSS': 'B+',
 'AGN': 'B-',
 'HUM': 'B+',
 'ALL': 'B+',
 'MAR': 'A-',
 'COST': 'A',
 'EMN': 'B+',
 'COF': 'B+',
 'DRI': 'A-',
 'NTAP': 'B',
 'HIG': 'B',
 'YUM': 'A',
 'RHI': 'A',
 'STZ': 'B+',
 'CTAS': 'A',
 'CMCSA': 'A',
 'FLS': 'B',
 'EXPD': 'A',
 'MTB': 'A-',
 'J': 'B',
 'LEG': 'A-',
 'LEN': 'B+',
 'HST': 'B',
 'MKC': 'A',
 'MYL': 'B-',
 'NBL': 'B-',
 'NI': 'B',
 'SJM': 'B+',
 'PSA': 'A-',
 'SYK': 'B+',
 'TSN': 'A',
 'UPS': 'B+',
 'VAR': 'B',
 'VNO': 'B',
 'WEC': 'A',
 'ZION': 'B+',
 'TROW': 'A',
 'HOG': 'A-',
 'FISV': 'B+',
 'TIF': 'B+',
 'XRAY': 'B',
 'FAST': 'A+',
 'APH': 'A',
 'PXD': 'B-',
 'DVN': 'B-',
 'LH': 'B',
 'VLO': 'B+',
 'NLOK': 'B-',
 'PBCT': 'A',
 'EOG': 'B',
 'EA': 'B',
 'COG': 'B',
 'XLNX': 'B+',
 'BIIB': 'B+',
 'KIM': 'B+',
 'GILD': 'B',
 'DHI': 'B+',
 'SBUX': 'A-',
 'INTU': 'A-',
 'MCHP': 'B',
 'EQR': 'B+',
 'SPG': 'A',
 'IVZ': 'A-',
 'AVB': 'B+',
 'PLD': 'B',
 'AIV': 'B',
 'ABC': 'B',
 'DVA': 'B+',
 'EL': 'A',
 'WAT': 'B',
 'CTXS': 'B',
 'TRV': 'B+',
 'ETFC': 'B',
 'NOV': 'B-',
 'DGX': 'A-',
 'AMZN': 'B',
 'RL': 'A',
 'BXP': 'B+',
 'CHRW': 'A',
 'VRSN': 'B+',
 'AMT': 'A-',
 'CTSH': 'A-',
 'EBAY': 'B-',
 'GS': 'B+',
 'NVDA': 'B+',
 'JNPR': 'B',
 'AKAM': 'B+',
 'EXPE': 'B+',
 'A': 'B',
 'MET': 'B+',
 'ISRG': 'B+',
 'MCO': 'A-',
 'TPR': 'B+',
 'MDLZ': 'B+',
 'PRU': 'B',
 'ZBH': 'B',
 'ANTM': 'A-',
 'PFG': 'A-',
 'CME': 'B+',
 'NDAQ': 'B+',
 'AIZ': 'A-',
 'CRM': 'B-',
 'MA': 'A+',
 'GOOGL': 'B+',
 'ICE': 'B+',
 'CF': 'B-',
 'AMP': 'A',
 'FIS': 'B+',
 'WU': 'B',
 'DFS': 'A-',
 'PM': 'B+',
 'CBRE': 'B+',
 'ABT': 'B',
 'HON': 'A',
 'AEP': 'B+',
 'BA': 'A',
 'BMY': 'B',
 'CPB': 'B',
 'CAT': 'B+',
 'CVX': 'B-',
 'KO': 'B+',
 'CL': 'B+',
 'ED': 'B+',
 'GLW': 'B-',
 'DE': 'B+',
 'DTE': 'A-',
 'D': 'B',
 'ETN': 'A',
 'XOM': 'B',
 'F': 'B-',
 'GD': 'A+',
 'GE': 'B-',
 'HAL': 'B-',
 'HSY': 'A',
 'IBM': 'A-',
 'IP': 'B+',
 'K': 'B+',
 'KMB': 'B+',
 'KR': 'A-',
 'SPGI': nan,
 'CVS': 'A',
 'MRK': 'B+',
 'ETR': 'B',
 'MMM': 'A',
 'MSI': 'B+',
 'NSC': 'A',
 'XEL': 'A',
 'FE': 'D',
 'PPG': 'A-',
 'SRE': 'B+',
 'PEP': 'B+',
 'PFE': 'A-',
 'EXC': 'B',
 'MO': 'B+',
 'COP': 'B-',
 'PG': 'A-',
 'PEG': 'B+',
 'AXP': 'A-',
 'AIG': 'B-',
 'AAPL': 'B+',
 'ADM': 'B+',
 'ADP': 'A',
 'BAX': 'B',
 'BDX': 'B+',
 'BF.B': 'A-',
 'CI': 'A',
 'CSX': 'A+',
 'JPM': 'A-',
 'CLX': 'A+',
 'CAG': 'B-',
 'TAP': 'B',
 'CMI': 'B+',
 'TGT': 'B+',
 'DIS': 'A+',
 'DUK': 'A-',
 'EMR': 'A',
 'NEE': 'A',
 'FDX': 'B+',
 'GIS': 'A',
 'GPC': 'A',
 'GWW': 'A',
 'HPQ': 'B',
 'INTC': 'B+',
 'IFF': 'A-',
 'JNJ': 'A-',
 'LLY': 'B',
 'LB': 'B',
 'LNC': 'B+',
 'MAS': 'B',
 'MCD': 'A',
 'BAC': 'B',
 'NEM': 'B-',
 'WFC': 'A-',
 'OXY': 'B-',
 'PCAR': 'A',
 'ROK': 'A-',
 'SLB': 'B-',
 'SHW': 'A+',
 'SNA': 'A+',
 'EIX': 'B',
 'SO': 'B+',
 'SWK': 'A',
 'TXN': 'A',
 'TXT': 'B',
 'UNP': 'A',
 'VFC': 'A-',
 'WMT': 'B+',
 'WBA': 'A-',
 'WY': 'B-',
 'WHR': 'B+',
 'WMB': 'B+',
 'XRX': 'B',
 'AMD': 'C',
 'ALK': 'B+',
 'AON': 'B+',
 'DXC': 'B-',
 'COO': 'B+',
 'DD': 'B-',
 'ATO': 'A-',
 'AJG': 'A',
 'LHX': 'A-',
 'HLT': 'B',
 'HFC': 'B',
 'TT': 'B+',
 'EVRG': 'A-',
 'RJF': 'A+',
 'ROL': 'A+',
 'AOS': 'A',
 'TFX': 'B+',
 'GL': 'A',
 'UDR': 'B',
 'RTX': 'A-',
 'LNT': 'A',
 'JKHY': 'A',
 'COTY': nan,
 'IT': 'B+',
 'NVR': 'B+',
 'PEAK': 'B',
 'CDNS': 'B',
 'DRE': 'B',
 'ABMD': 'B-',
 'MXIM': 'B+',
 'FRC': 'A-',
 'MGM': 'B-',
 'WRB': 'B+',
 'IEX': 'A',
 'SIVB': 'B+',
 'TMUS': nan,
 'IQV': nan,
 'TWTR': nan,
 'PAYC': nan,
 'KEYS': nan,
 'ANET': nan,
 'HOLX': 'C',
 'CFG': nan,
 'IDXX': 'B+',
 'ZBRA': 'B',
 'ODFL': 'A-',
 'SNPS': 'B',
 'STE': 'B+',
 'FTV': nan,
 'HWM': 'B-',
 'CDW': 'A-',
 'LW': nan,
 'REG': 'B',
 'INCY': 'B-',
 'MAA': 'B+',
 'ALB': 'B',
 'CPRT': 'B+',
 'IR': 'B',
 'FTI': 'B-',
 'RMD': 'B+',
 'BKR': nan,
 'DOW': nan,
 'FOXA': nan,
 'CTVA': nan,
 'OTIS': nan,
 'CARR': nan,
 'DISH': 'B',
 'WAB': 'B+',
 'RE': 'B',
 'ANSS': 'B+',
 'TTWO': 'B-',
 'ARE': 'B-',
 'MTD': 'B+',
 'AMCR': 'B+',
 'NCLH': nan,
 'SBAC': 'B-',
 'CHTR': 'B-',
 'PKG': 'A-',
 'ALGN': 'B+',
 'GPN': 'B+',
 'CNC': 'B+',
 'TDG': 'B+',
 'LKQ': 'B+',
 'MKTX': 'A',
 'DLR': 'A-',
 'LVS': 'B+',
 'CE': 'B+',
 'INFO': 'B',
 'UAA': 'B+',
 'LDOS': 'B',
 'LYV': 'C',
 'FANG': nan,
 'NOW': nan,
 'IPGP': 'B+',
 'BR': 'A',
 'CXO': 'B-',
 'MSCI': 'B+',
 'ULTA': 'B+',
 'AWK': 'A-',
 'FTNT': 'B',
 'CBOE': 'B+',
 'FLT': 'B+',
 'HII': 'B+',
 'FBHS': nan,
 'AAL': 'B-',
 'SWKS': 'B+',
 'AME': 'A',
 'BRK.B': 'B+',
 'CHD': 'A',
 'DAL': 'B',
 'DG': 'A',
 'FMC': 'B',
 'FRT': 'A-',
 'GM': 'B',
 'WELL': 'A-',
 'KHC': 'B+',
 'HP': 'B-',
 'HRL': 'A+',
 'JBHT': 'A+',
 'KMI': 'B',
 'KSU': 'B+',
 'LRCX': 'B+',
 'ES': 'A',
 'OKE': 'A-',
 'PNR': 'B+',
 'PVH': 'A-',
 'ROST': 'A+',
 'UAL': 'B',
 'UHS': 'A+',
 'WDC': 'B-',
 'CERN': 'B+',
 'ZTS': nan,
 'ABBV': nan,
 'NWSA': nan,
 'SYF': nan,
 'HCA': 'B+',
 'REGN': 'B',
 'MNST': 'B+',
 'VRTX': 'B-',
 'PYPL': nan,
 'PRGO': 'B-',
 'ROP': 'A',
 'MHK': 'B',
 'HPE': nan,
 'CB': 'B+',
 'ORLY': 'B+',
 'RCL': 'B+',
 'FLIR': 'B',
 'BWA': 'B+',
 'MLM': 'A-',
 'TSCO': 'A+',
 'WRK': 'B',
 'ESS': 'A-',
 'O': 'A-',
 'DLTR': 'B',
 'HSIC': 'B+',
 'ALXN': 'B',
 'IRM': 'B',
 'KMX': 'B+',
 'QRVO': 'C',
 'SLG': 'B-',
 'URI': 'B',
 'PWR': 'B+',
 'NLSN': nan,
 'VTR': 'B+',
 'RSG': 'A-',
 'CCI': 'B',
 'APTV': 'D',
 'BKNG': 'B+',
 'FFIV': 'B+',
 'BLK': 'A',
 'EW': 'B+',
 'NRG': 'B',
 'ILMN': 'B+',
 'EQIX': 'B',
 'GRMN': 'A-',
 'ACN': 'A',
 'ADS': 'B+',
 'WLTW': 'B',
 'AAP': 'A',
 'NFLX': 'B',
 'WYNN': 'B',
 'STX': 'B',
 'EXR': 'A-',
 'MOS': 'B-',
 'DISCA': 'B',
 'CMG': 'B+',
 'FB': nan,
 'PSX': nan,
 'HBI': 'B+',
 'TEL': 'B+',
 'V': 'A',
 'ATVI': 'A-',
 'VRSK': 'B+',
 'AVGO': 'B',
 'MPC': nan,
 'XYL': nan,
 'CPRI': nan,
 'LYB': 'B+',
 'ALLE': nan}

In [11]:
len(priceData.columns)

500

In [34]:
dropCols = []
for col in priceData.columns:
    if priceData[col].dropna().index[0] > pd.to_datetime('2016-01-01'):
        print(col, priceData[col].dropna().index[0])
        dropCols.append(col)

FTV 2016-06-13 00:00:00
HWM 2016-11-01 00:00:00
LW 2016-11-01 00:00:00
IR 2017-05-12 00:00:00
FTI 2017-01-17 00:00:00
BKR 2017-07-05 00:00:00
DOW 2019-03-20 00:00:00
FOXA 2019-03-13 00:00:00
CTVA 2019-05-24 00:00:00
OTIS 2020-03-19 00:00:00
CARR 2020-03-19 00:00:00
AMCR 2019-06-11 00:00:00

In [35]:
# choose price data after 2015-01-01
final = priceData.loc[priceData.index > '2016-01-01']
# remove all non rows
final.dropna(axis=0, how='all', inplace=True)
# remove stocks that listed after 2016-01-01
final.drop(dropCols, axis=1, inplace=True)

final.isnull().sum().sum()

/opt/conda/lib/python3.7/site-packages/ipykernel_launcher.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  after removing the cwd from sys.path.
/opt/conda/lib/python3.7/site-packages/pandas/core/frame.py:4097: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  errors=errors,

0

In [37]:
final.head(3)

,PNW,APD,HES,AFL,AMGN,ADI,APA,AMAT,ADSK,AVY,...,TEL,V,ATVI,VRSK,AVGO,MPC,XYL,CPRI,LYB,ALLE
2016-01-04,64.31,128.21,48.40,58.79,159.00,54.24,44.25,18.31,60.01,61.68,...,63.47,76.06,38.05,75.36,142.07,51.68,35.92,39.39,86.28,64.88
2016-01-05,63.96,128.47,47.68,59.17,159.00,54.73,43.50,18.47,60.39,61.14,...,63.44,76.25,37.79,75.21,143.14,51.40,36.06,40.50,87.82,64.57
2016-01-06,63.92,124.86,46.68,58.33,155.01,53.07,42.10,18.17,59.46,60.86,...,62.47,75.00,36.32,74.01,134.57,49.30,36.43,39.98,85.11,63.62

In [38]:
final.tail(3)

,PNW,APD,HES,AFL,AMGN,ADI,APA,AMAT,ADSK,AVY,...,TEL,V,ATVI,VRSK,AVGO,MPC,XYL,CPRI,LYB,ALLE
2020-04-15,79.01,219.27,36.00,36.19,224.99,100.73,7.12,51.310,168.57,106.82,...,67.52,168.70,62.630,147.56,261.00,24.81,68.53,13.55,55.90,96.38
2020-04-16,79.88,214.44,34.86,35.71,225.00,101.52,7.96,51.870,171.46,107.66,...,65.88,167.11,66.454,148.31,261.76,24.01,66.76,13.55,52.46,94.37
2020-04-17,80.59,217.46,32.99,36.23,236.83,103.96,7.45,53.635,176.08,107.24,...,65.23,169.65,66.500,153.48,263.22,22.61,68.73,13.09,50.26,96.37

In [39]:
train = final.loc[final.index < '2020-01-01']
test = final.loc[final.index > '2020-01-01']

In [40]:
corr = train.corr()

In [41]:
train.columns.values

array(['PNW', 'APD', 'HES', 'AFL', 'AMGN', 'ADI', 'APA', 'AMAT', 'ADSK',
       'AVY', 'BLL', 'BK', 'VZ', 'BBY', 'HRB', 'CAH', 'CTL', 'CMA', 'C',
       'CMS', 'DHR', 'DOV', 'OMC', 'PKI', 'ECL', 'EFX', 'FITB', 'RF',
       'USB', 'BEN', 'GPS', 'HAS', 'HD', 'CNP', 'HBAN', 'ITW', 'IPG',
       'JCI', 'KLAC', 'LMT', 'L', 'LOW', 'MRO', 'MMC', 'MCK', 'MDT', 'MU',
       'NWL', 'NKE', 'JWN', 'NTRS', 'NOC', 'NUE', 'PNC', 'PH', 'PAYX',
       'PPL', 'PHM', 'SEE', 'KEY', 'LUV', 'T', 'STT', 'SYY', 'TMO', 'AEE',
       'UNH', 'VMC', 'TJX', 'TFC', 'MS', 'MSFT', 'ORCL', 'ADBE', 'UNM',
       'PGR', 'CCL', 'VIAC', 'SCHW', 'WM', 'FCX', 'CINF', 'CSCO', 'AZO',
       'AES', 'QCOM', 'LIN', 'BSX', 'KSS', 'AGN', 'HUM', 'ALL', 'MAR',
       'COST', 'EMN', 'COF', 'DRI', 'NTAP', 'HIG', 'YUM', 'RHI', 'STZ',
       'CTAS', 'CMCSA', 'FLS', 'EXPD', 'MTB', 'J', 'LEG', 'LEN', 'HST',
       'MKC', 'MYL', 'NBL', 'NI', 'SJM', 'PSA', 'SYK', 'TSN', 'UPS',
       'VAR', 'VNO', 'WEC', 'ZION', 'TROW', 'HOG', 'FISV', 'TIF', 'XRAY',
       'FAST', 'APH', 'PXD', 'DVN', 'LH', 'VLO', 'NLOK', 'PBCT', 'EOG',
       'EA', 'COG', 'XLNX', 'BIIB', 'KIM', 'GILD', 'DHI', 'SBUX', 'INTU',
       'MCHP', 'EQR', 'SPG', 'IVZ', 'AVB', 'PLD', 'AIV', 'ABC', 'DVA',
       'EL', 'WAT', 'CTXS', 'TRV', 'ETFC', 'NOV', 'DGX', 'AMZN', 'RL',
       'BXP', 'CHRW', 'VRSN', 'AMT', 'CTSH', 'EBAY', 'GS', 'NVDA', 'JNPR',
       'AKAM', 'EXPE', 'A', 'MET', 'ISRG', 'MCO', 'TPR', 'MDLZ', 'PRU',
       'ZBH', 'ANTM', 'PFG', 'CME', 'NDAQ', 'AIZ', 'CRM', 'MA', 'GOOGL',
       'ICE', 'CF', 'AMP', 'FIS', 'WU', 'DFS', 'PM', 'CBRE', 'ABT', 'HON',
       'AEP', 'BA', 'BMY', 'CPB', 'CAT', 'CVX', 'KO', 'CL', 'ED', 'GLW',
       'DE', 'DTE', 'D', 'ETN', 'XOM', 'F', 'GD', 'GE', 'HAL', 'HSY',
       'IBM', 'IP', 'K', 'KMB', 'KR', 'SPGI', 'CVS', 'MRK', 'ETR', 'MMM',
       'MSI', 'NSC', 'XEL', 'FE', 'PPG', 'SRE', 'PEP', 'PFE', 'EXC', 'MO',
       'COP', 'PG', 'PEG', 'AXP', 'AIG', 'AAPL', 'ADM', 'ADP', 'BAX',
       'BDX', 'BF.B', 'CI', 'CSX', 'JPM', 'CLX', 'CAG', 'TAP', 'CMI',
       'TGT', 'DIS', 'DUK', 'EMR', 'NEE', 'FDX', 'GIS', 'GPC', 'GWW',
       'HPQ', 'INTC', 'IFF', 'JNJ', 'LLY', 'LB', 'LNC', 'MAS', 'MCD',
       'BAC', 'NEM', 'WFC', 'OXY', 'PCAR', 'ROK', 'SLB', 'SHW', 'SNA',
       'EIX', 'SO', 'SWK', 'TXN', 'TXT', 'UNP', 'VFC', 'WMT', 'WBA', 'WY',
       'WHR', 'WMB', 'XRX', 'AMD', 'ALK', 'AON', 'DXC', 'COO', 'DD',
       'ATO', 'AJG', 'LHX', 'HLT', 'HFC', 'TT', 'EVRG', 'RJF', 'ROL',
       'AOS', 'TFX', 'GL', 'UDR', 'RTX', 'LNT', 'JKHY', 'COTY', 'IT',
       'NVR', 'PEAK', 'CDNS', 'DRE', 'ABMD', 'MXIM', 'FRC', 'MGM', 'WRB',
       'IEX', 'SIVB', 'TMUS', 'IQV', 'TWTR', 'PAYC', 'KEYS', 'ANET',
       'HOLX', 'CFG', 'IDXX', 'ZBRA', 'ODFL', 'SNPS', 'STE', 'CDW', 'REG',
       'INCY', 'MAA', 'ALB', 'CPRT', 'RMD', 'DISH', 'WAB', 'RE', 'ANSS',
       'TTWO', 'ARE', 'MTD', 'NCLH', 'SBAC', 'CHTR', 'PKG', 'ALGN', 'GPN',
       'CNC', 'TDG', 'LKQ', 'MKTX', 'DLR', 'LVS', 'CE', 'INFO', 'UAA',
       'LDOS', 'LYV', 'FANG', 'NOW', 'IPGP', 'BR', 'CXO', 'MSCI', 'ULTA',
       'AWK', 'FTNT', 'CBOE', 'FLT', 'HII', 'FBHS', 'AAL', 'SWKS', 'AME',
       'BRK.B', 'CHD', 'DAL', 'DG', 'FMC', 'FRT', 'GM', 'WELL', 'KHC',
       'HP', 'HRL', 'JBHT', 'KMI', 'KSU', 'LRCX', 'ES', 'OKE', 'PNR',
       'PVH', 'ROST', 'UAL', 'UHS', 'WDC', 'CERN', 'ZTS', 'ABBV', 'NWSA',
       'SYF', 'HCA', 'REGN', 'MNST', 'VRTX', 'PYPL', 'PRGO', 'ROP', 'MHK',
       'HPE', 'CB', 'ORLY', 'RCL', 'FLIR', 'BWA', 'MLM', 'TSCO', 'WRK',
       'ESS', 'O', 'DLTR', 'HSIC', 'ALXN', 'IRM', 'KMX', 'QRVO', 'SLG',
       'URI', 'PWR', 'NLSN', 'VTR', 'RSG', 'CCI', 'APTV', 'BKNG', 'FFIV',
       'BLK', 'EW', 'NRG', 'ILMN', 'EQIX', 'GRMN', 'ACN', 'ADS', 'WLTW',
       'AAP', 'NFLX', 'WYNN', 'STX', 'EXR', 'MOS', 'DISCA', 'CMG', 'FB',
       'PSX', 'HBI', 'TEL', 'V', 'ATVI', 'VRSK', 'AVGO', 'MPC', 'XYL',
       'CPRI', 'LYB', 'ALLE'], dtype=object)

In [42]:
len(sectorMap.keys()), len(ratingMap.keys())

(500, 500)

In [43]:
corr.to_csv(os.getcwd() + '/clean_data/corr.csv', index=True)
train.to_csv(os.getcwd() + '/clean_data/train.csv', index=True)
test.to_csv(os.getcwd() + '/clean_data/test.csv', index=True)

In [64]:
final_sectorMap = {}
final_ratingMap = {}
for k, v in sectorMap.items():
    if k in train.columns.values.tolist():
        final_sectorMap[k] = v
        final_ratingMap[k] = ratingMap[k]

In [65]:
len(list(final_sectorMap.keys())), len(list(final_ratingMap.keys())), len(list(final_sectorMap.values())), len(list(final_ratingMap.keys())),

(488, 488, 488, 488)

In [66]:
import pickle        

with open(os.getcwd() + '/clean_data/sectorMap.pkl', 'wb') as f:
    pickle.dump(final_sectorMap, f, pickle.HIGHEST_PROTOCOL)
    
with open(os.getcwd() + '/clean_data/ratingMap.pkl', 'wb') as f:
    pickle.dump(final_ratingMap, f, pickle.HIGHEST_PROTOCOL)

In [45]:
from scipy.stats import norm

In [58]:
varDF = pd.DataFrame(index=train.columns, columns=[0.1, 0.05, 0.01])

for alpha in varDF.columns:
    varDF[alpha] = train.pct_change().dropna(axis=0, how='all').apply(
        lambda s: norm.ppf(alpha, s.mean(), s.std()), axis=0
    )

In [60]:
varDF.head()

          0.10      0.05      0.01
PNW  -0.012689 -0.016394 -0.023344
APD  -0.013999 -0.018157 -0.025956
HES  -0.031340 -0.040398 -0.057389
AFL  -0.023784 -0.030564 -0.043282
AMGN -0.016507 -0.021328 -0.030371

In [61]:
varDF.tail()

          0.10      0.05      0.01
MPC  -0.025485 -0.032807 -0.046541
XYL  -0.016398 -0.021295 -0.030480
CPRI -0.030168 -0.038785 -0.054949
LYB  -0.020982 -0.026992 -0.038265
ALLE -0.016252 -0.021068 -0.030100

In [62]:
varDF.to_csv(os.getcwd() + '/clean_data/var.csv', index=True)

In [67]:
inv_sectorMap = {i: [] for i in set(list(final_sectorMap.values()))}
for stock, sector in final_sectorMap.items():
    inv_sectorMap[sector].append(stock)
    
with open(os.getcwd() + '/clean_data/inv_sectorMap.pkl', 'wb') as f:
    pickle.dump(inv_sectorMap, f, pickle.HIGHEST_PROTOCOL)

In [5]:
tmp = pd.read_csv(os.getcwd() + '/dataset/7b76f81ae9c44ab7.csv')
tmp['datadate'] = pd.to_datetime(tmp['datadate'], format='%Y/%m/%d')

In [8]:
priceData = pd.DataFrame([])

for index, row in tqdm.tqdm_notebook(tmp.iterrows(), desc='2nd loop'):
    if row['tic'] in stockList:
        priceData.loc[row['datadate'], row['tic']] = row['prcod']

HBox(children=(IntProgress(value=1, bar_style='info', description='2nd loop', max=1, style=ProgressStyle(descr…

In [9]:
priceData.head()

,AAL,PNW,ABT,AMD,APD,ALK,HON,SWKS,HES,AEP,...,CBOE,FLT,HII,MPC,FBHS,XYL,CPRI,CBRE,LYB,ALLE
2015-01-02,54.28,68.58,45.25,2.70,143.39,60.54,100.20,73.60,73.19,60.88,...,63.88,149.04,112.49,89.55,45.62,38.40,75.56,34.51,79.94,55.49
2015-01-05,54.37,68.62,44.80,2.67,144.36,60.81,99.90,73.10,72.64,61.10,...,63.23,150.28,111.65,90.85,44.46,37.34,74.32,34.31,78.79,54.73
2015-01-06,54.27,68.20,44.99,2.65,141.49,59.78,98.30,72.20,69.88,60.42,...,65.75,143.41,111.74,89.13,44.39,35.70,69.27,34.04,76.44,55.00
2015-01-07,53.38,68.80,44.73,2.63,141.83,59.06,99.07,71.47,70.30,60.71,...,66.09,143.36,115.06,89.64,43.49,35.87,67.51,33.89,75.14,55.09
2015-01-08,53.48,70.21,45.19,2.59,142.90,60.00,99.64,72.00,70.21,61.63,...,67.58,144.26,115.08,89.97,44.26,36.01,69.10,34.24,76.05,55.71

In [10]:
priceData.tail()

,AAL,PNW,ABT,AMD,APD,ALK,HON,SWKS,HES,AEP,...,CBOE,FLT,HII,MPC,FBHS,XYL,CPRI,CBRE,LYB,ALLE
2015-12-24,43.27,64.44,44.94,2.88,132.91,82.11,104.87,79.17,51.11,58.14,...,64.81,145.11,128.45,52.45,55.96,37.08,41.53,34.88,89.45,65.84
2015-12-28,43.62,64.12,44.92,2.91,132.52,82.13,104.23,78.81,49.43,58.16,...,65.29,144.80,129.31,52.09,56.00,36.97,40.64,34.49,87.71,65.45
2015-12-29,43.25,64.92,45.28,3.04,133.70,82.55,105.20,79.43,49.80,58.80,...,65.91,144.99,129.40,52.34,56.70,37.20,40.89,34.98,87.77,67.04
2015-12-30,43.64,65.03,45.85,2.99,132.09,82.77,105.40,80.18,48.49,58.94,...,65.96,145.36,129.18,51.93,56.34,37.10,41.00,35.09,88.07,66.70
2015-12-31,42.54,65.05,45.11,2.97,131.45,81.00,104.07,78.91,47.74,58.82,...,65.45,142.39,127.06,51.99,56.16,36.67,40.08,34.59,87.00,66.26

In [11]:
priceData.to_csv(os.getcwd() + '/clean_data/test2.csv')